[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "atlas-python"
version = "0.1.0"
description = "Rust Belt Atlas prototype CLI and scoring engine"
readme = "README.md"
requires-python = ">=3.11"
authors = [
  {name = "Rust Belt Team"}
]
dependencies = [
  "jsonschema>=4.21",
  "numpy>=1.26",
  "pandas>=2.1",
  "pyarrow>=14",
]

[project.optional-dependencies]
dev = [
  "pytest>=8.0"
]

[project.scripts]
rustbelt-atlas = "atlas.cli.__main__:main"

[tool.pytest.ini_options]
markers = [
    "integration: end-to-end CLI tests",
]
